using System.Collections;
using System.Collections.Generic;

public static class FileClassifier {

    public enum FileType {
        Folder,
        Document,
        Executable,
        Script,
        Image,
        Video,
        Audio,
        Archive,
        DiskImage,
        Windows,
        Library,
        Unknown,
        Source,
        Data,
        Font,
        Internet,
        Presentation,
        Spreadsheet,
        Text
    }

    public static Dictionary<FileType, string> FileTypeNames = new Dictionary<FileType, string>() {
        { FileType.Folder, "Folder" },
        { FileType.Document, "Document" },
        { FileType.Executable, "Executable" },
        { FileType.Script, "Script" },
        { FileType.Image, "Image" },
        { FileType.Video, "Video" },
        { FileType.Audio, "Audio" },
        { FileType.Archive, "Archive" },
        { FileType.DiskImage, "DiskImage" },
        { FileType.Windows, "Windows" },
        { FileType.Library, "Library" },
        { FileType.Unknown, "Unknown" },
        { FileType.Source, "Source" },
        { FileType.Data, "Data" },
        { FileType.Font, "Font" },
        { FileType.Internet, "Internet" },
        { FileType.Presentation, "Presentation" },
        { FileType.Spreadsheet, "Spreadsheet" },
        { FileType.Text, "Text" }
    };

    public static Dictionary<string, FileType> extTypes = new Dictionary<string, FileType>() {
        #region type definitions
        { "video/*", FileType.Video },
        { "image/*", FileType.Image },
        { "audio/*", FileType.Audio },
        { "font/*", FileType.Font },
        { "text/plain", FileType.Text },
        { "text/css", FileType.Internet },
        { "text/csv", FileType.Spreadsheet },
        { "text/xml", FileType.Document },
        { "text/dlm", FileType.Unknown },
        { "text/x-setext", FileType.Text },
        { "text/x-hdml", FileType.Internet },
        { "text/x-component", FileType.Internet },
        { "text/html", FileType.Internet },
        { "text/webviewhtml", FileType.Internet },
        { "text/x-ms-iqy", FileType.Internet },
        { "text/jscript", FileType.Source },
        { "text/x-html-insertion", FileType.Internet },
        { "text/x-ms-rqy", FileType.Internet },
        { "text/richtext", FileType.Document },
        { "text/scriptlet", FileType.Script },
        { "text/sgml", FileType.Text },
        { "text/tab-separated-values", FileType.Spreadsheet },
        { "text/vbscript", FileType.Script },
        { "text/x-vcard", FileType.Data },
        { "text/vtt", FileType.Data },
        { "text/vnd.wap.wml", FileType.Internet },
        { "text/vnd.wap.wmlscript", FileType.Internet },
        { "text/source", FileType.Source },
        { "text/script", FileType.Script },
        { "message/rfc822", FileType.Internet },
        { "application/acad", FileType.Data },
        { "application/annodex", FileType.Data },
        { "application/atom+xml", FileType.Internet },
        { "application/directx", FileType.Data },
        { "application/diskimage", FileType.DiskImage },
        { "application/envoy", FileType.Document },
        { "application/etl", FileType.Text },
        { "application/font-*", FileType.Font },
        { "application/fractals", FileType.Data },
        { "application/fsharp-script", FileType.Script },
        { "application/futuresplash", FileType.Data },
        { "application/gpx+xml", FileType.Internet },
        { "application/hta", FileType.Executable },
        { "application/internet-property-stream", FileType.Internet },
        { "application/java-archive", FileType.Executable },
        { "application/javascript", FileType.Script },
        { "application/json", FileType.Text },
        { "application/liquidmotion", FileType.Data },
        { "application/mac-binhex40", FileType.Archive },
        { "application/mbox", FileType.Data },
        { "application/mpeg", FileType.Video },
        { "application/msaccess*", FileType.Data },
        { "application/ms-vsi", FileType.Archive },
        { "application/msword", FileType.Document },
        { "application/oda", FileType.Document },
        { "application/ogg", FileType.Audio },
        { "application/olescript", FileType.Script },
        { "application/onenote", FileType.Document },
        { "application/opensearchdescription+xml", FileType.Data },
        { "application/pdf", FileType.Document },
        { "application/pkcs*", FileType.Data },
        { "application/pkix-crl", FileType.Data },
        { "application/postscript", FileType.Data },
        { "application/PowerShell", FileType.Script },
        { "application/rat-file", FileType.Text },
        { "application/rtf", FileType.Document },
        { "application/shared-library", FileType.Library },
        { "application/sdp", FileType.Video },
        { "application/step", FileType.Data },
        { "application/streamingmedia", FileType.Video },
        { "application/vnd.adobe.air-application-installer-package+zip", FileType.Archive },
        { "application/vnd.android.package-archive", FileType.Archive },
        { "application/vnd.fdf", FileType.Data },
        { "application/vnd.ms-excel*", FileType.Spreadsheet },
        { "application/vnd.ms-fontobject", FileType.Font },
        { "application/vnd.ms-mediapackage", FileType.Image },
        { "application/vnd.ms-office.calx", FileType.Document },
        { "application/vnd.ms-officetheme", FileType.Data },
        { "application/vnd.ms-outlook", FileType.Data },
        { "application/vnd.ms-pki*", FileType.Data },
        { "application/vnd.ms-powerpoint*", FileType.Presentation },
        { "application/vnd.ms-project", FileType.Document },
        { "application/vnd.ms-visio.viewer", FileType.Document },
        { "application/vnd.ms-word.document.macroEnabled.12", FileType.Document },
        { "application/vnd.ms-word.template.macroEnabled.12", FileType.Document },
        { "application/vnd.ms-works", FileType.Document },
        { "application/vnd.ms-wpl", FileType.Audio },
        { "application/vnd.ms-xpsdocument", FileType.Document },
        { "application/vnd.microsoft.portable-executable", FileType.Windows },
        { "application/vnd.oasis.opendocument.chart", FileType.Document },
        { "application/vnd.oasis.opendocument.database", FileType.Data },
        { "application/vnd.oasis.opendocument.formula", FileType.Data },
        { "application/vnd.oasis.opendocument.graphics*", FileType.Image },
        { "application/vnd.oasis.opendocument.image", FileType.Image },
        { "application/vnd.oasis.opendocument.presentation*", FileType.Presentation },
        { "application/vnd.oasis.opendocument.spreadsheet*", FileType.Spreadsheet },
        { "application/vnd.oasis.opendocument.text", FileType.Text },
        { "application/vnd.openofficeorg.extension", FileType.Data },
        { "application/vnd.openxmlformats-officedocument.presentationml.*", FileType.Presentation },
        { "application/vnd.openxmlformats-officedocument.spreadsheetml.*", FileType.Spreadsheet },
        { "application/vnd.openxmlformats-officedocument.wordprocessingml.*", FileType.Document },
        { "application/vnd.rn-realmedia", FileType.Video },
        { "application/vnd.rn-rn_music_package", FileType.Audio },
        { "application/vnd.visio", FileType.Document },
        { "application/vnd.wap.wmlc", FileType.Internet },
        { "application/vnd.wap.wmlscriptc", FileType.Internet },
        { "application/vsix", FileType.Data },
        { "application/wasm", FileType.Executable },
        { "application/windows-library+xml", FileType.Library },
        { "application/windows-search-connector+xml", FileType.Data },
        { "application/winhlp", FileType.Document },
        { "application/wlmoviemaker", FileType.Video },
        { "application/x-7z-compressed", FileType.Archive },
        { "application/xaml+xml", FileType.Text },
        { "application/x-bcpio", FileType.Archive },
        { "application/x-bridge-url", FileType.Data },
        { "application/x-cdf", FileType.Document },
        { "application/x-compress", FileType.Archive },
        { "application/x-compressed", FileType.Archive },
        { "application/x-cpio", FileType.Archive },
        { "application/x-csh", FileType.Script },
        { "application/x-director", FileType.Video },
        { "application/x-dvi", FileType.Document },
        { "application/x-dxf", FileType.Image },
        { "application/x-gtar", FileType.Archive },
        { "application/x-gzip", FileType.Archive },
        { "application/x-hdf", FileType.Data },
        { "application/xhtml+xml", FileType.Internet },
        { "application/x-internet-signup", FileType.Internet },
        { "application/x-itunes-ipa", FileType.Archive },
        { "application/x-itunes-ipg", FileType.Archive },
        { "application/x-itunes-ipsw", FileType.Archive },
        { "application/x-itunes-ite", FileType.Internet },
        { "application/x-itunes-itlp", FileType.Audio },
        { "application/x-itunes-itms", FileType.Internet },
        { "application/x-itunes-itpc", FileType.Internet },
        { "application/x-java-*", FileType.Executable },
        { "application/x-koan", FileType.Document },
        { "application/x-latex", FileType.Document },
        { "application/x-miva-compiled", FileType.Video },
        { "application/xml", FileType.Document },
        { "application/x-mmxp", FileType.Data },
        { "application/x-msaccess", FileType.Data },
        { "application/x-ms-application", FileType.Executable },
        { "application/x-mscardfile", FileType.Data },
        { "application/x-msclip", FileType.Video },
        { "application/x-msdownload", FileType.Internet },
        { "application/x-ms-license", FileType.Text },
        { "application/x-ms-manifest", FileType.Data },
        { "application/x-msmediaview", FileType.Video },
        { "application/x-msmetafile", FileType.Data },
        { "application/x-msmoney", FileType.Data },
        { "application/x-mspublisher", FileType.Document },
        { "application/x-ms-reader", FileType.Document },
        { "application/x-msschedule", FileType.Data },
        { "application/x-msterminal", FileType.Data },
        { "application/x-ms-wmd", FileType.Internet },
        { "application/x-ms-wmz", FileType.Video },
        { "application/x-mswrite", FileType.Document },
        { "application/x-ms-xbap", FileType.Executable },
        { "application/x-netcdf", FileType.Document },
        { "application/x-perfmon", FileType.Data },
        { "application/x-pkcs12", FileType.Data },
        { "application/x-pkcs7-*", FileType.Data },
        { "application/x-podcast", FileType.Audio },
        { "application/x-quicktimeplayer", FileType.Video },
        { "application/x-rar-compressed", FileType.Archive },
        { "application/x-safari-safariextz", FileType.Data },
        { "application/x-safari-webarchive", FileType.Internet },
        { "application/x-sh", FileType.Script },
        { "application/x-shar", FileType.Archive },
        { "application/x-shockwave-flash", FileType.Executable },
        { "application/x-silverlight-app", FileType.Executable },
        { "application/x-smaf", FileType.Audio },
        { "application/xspf+xml", FileType.Audio },
        { "application/x-stuffit", FileType.Archive },
        { "application/x-sv4cpio", FileType.Archive },
        { "application/x-sv4crc", FileType.Data },
        { "application/x-tar", FileType.Archive },
        { "application/x-tcl", FileType.Script },
        { "application/x-tex", FileType.Document },
        { "application/x-texinfo", FileType.Document },
        { "application/x-ustar", FileType.Archive },
        { "application/x-wais-source", FileType.Source },
        { "application/x-wlpg3-detect", FileType.Executable },
        { "application/x-wlpg-detect", FileType.Executable },
        { "application/x-x509-ca-cert", FileType.Data },
        { "application/x-zip-compressed", FileType.Archive },
        { "application/zip", FileType.Archive }
        #endregion
    };

    public static FileType GetFileType(string extension) {
        string mimeType = MimeTypes.MimeTypeMap.GetMimeType(extension);
        if (extTypes.ContainsKey(mimeType)) return extTypes[mimeType];
        for (; mimeType.Length > 0; mimeType = mimeType.Remove(mimeType.Length - 1)) if (extTypes.ContainsKey(mimeType + "*")) return extTypes[mimeType + "*"];
        return FileType.Unknown;
    }

    private static string[] sizes = { "B", "KB", "MB", "GB", "TB" };

    public static string GetFileSize(long length) {
        double len = length;
        int order = 0;
        while (len >= 1024 && order < sizes.Length - 1) {
            order++;
            len = len / 1024;
        }
        return string.Format("{0:0.##} {1}", len, sizes[order]);
    }

}
